swagger: "2.0"
info:
  title: Product API
  description: API for managing and searching products
  version: 1.0.0

host: localhost:8001
basePath: /products
schemes:
  - http

tags:
  - name: Products
    description: The product service API

definitions:
  ImageDTO:
    type: object
    properties:
      imageName:
        type: string
        example: "image_name_1"
      imageBase64:
        format: byte
        description: Base64 encoded image string
        example: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwkHBgoJG..."

  Product:
    type: object
    properties:
      productId:
        type: integer
        example: 123
      ownerId:
        type: integer
        example: 456
      productName:
        type: string
        example: "Sample Product"
      price:
        type: number
        format: double
        example: 19.99
      tags:
        type: array
        items:
          type: string
        example: ["Tag1", "Tag2"]
      condition:
        type: string
        example: "New"
      images:
        type: array
        items:
          $ref: "#/definitions/ImageDTO"
      totalQuantity:
        type: integer
        example: 100
      currentQuantity:
        type: integer
        example: 50
      createdOn:
        type: string
        format: date-time
        example: "2024-09-12 12:20:35.655023"
      categoryName:
        type: string
        example: "Electronics"
      description:
        type: string
        example: "This is a sample product description."

  ProductSearchRangeResponse:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: "#/definitions/ProductSearch"
        description: List of found products in the range
      total_count:
        type: integer
        description: Total count of matched products
        example: 100

  ProductSearch:
    type: object
    properties:
      productId:
        type: integer
        example: 2
      ownerId:
        type: integer
        example: 4
      ownerUsername:
        type: string
        example: "john_doe"
      productName:
        type: string
        example: "Apple watch"
      price:
        type: number
        format: double
        example: 499.99
      condition:
        type: string
        example: "New"
      currentQuantity:
        type: integer
        example: 50
      createdOn:
        type: string
        format: date-time
        example: "2024-09-12 12:20:35.655023"
      score:
        type: number
        format: float
        example: 0.15
      image:
        $ref: "#/definitions/ImageDTO"

  ProductReadPreview:
    type: object
    properties:
      productId:
        type: integer
        example: 2
      ownerId:
        type: integer
        example: 4
      productName:
        type: string
        example: "Apple watch"
      price:
        type: number
        format: double
        example: 499.99
      condition:
        type: string
        example: "New"
      currentQuantity:
        type: integer
        example: 50
      createdOn:
        type: string
        format: date-time
        example: "2024-09-12 12:20:35.655023"
      image:
        $ref: "#/definitions/ImageDTO"

  ProductReadOwnerResponse:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: "#/definitions/ProductReadPreview"
        description: List of found products in the range
      total_count:
        type: integer
        description: Total count of matched products
        example: 100

  ProductCreationRequest:
    type: object
    properties:
      productName:
        type: string
        example: "Apple Watch"
      price:
        type: number
        format: double
        example: 499.99
      tags:
        type: array
        items:
          type: string
        example: ["apple", "watch"]
      condition:
        type: string
        example: "New"
      imageBase64List:
        type: array
        items:
          type: string
        example:
          [
            "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwkHBgoJG...",
            "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwkHBgoJG...",
          ]
      totalQuantity:
        type: integer
        example: 10
      category:
        type: string
        example: "Electronics"
      description:
        type: string
        example: "Latest Apple Watch."

  ProductUpdateRequest:
    type: object
    properties:
      productId:
        type: integer
        example: 12
      productName:
        type: string
        example: "Apple watch"
      price:
        type: number
        format: double
        example: 499.99
      tags:
        type: array
        items:
          type: string
        example: ["apple", "watch"]
      condition:
        type: string
        example: "Used"
      deleteImageList:
        type: array
        items:
          type: string
        example: ["image_name_to_delete_1", "image_name_to_delete_2"]
      newImageBase64List:
        type: array
        items:
          type: string
        example:
          [
            "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwkHBgoJG...",
            "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwkHBgoJG...",
          ]
      totalQuantity:
        type: integer
        example: 10
      currentQuantity:
        type: integer
        example: 5
      category:
        type: string
        example: "Electronics"
      description:
        type: string
        example: "Latest Apple Watch."

  Category:
    type: object
    properties:
      id:
        type: integer
        example: 1
      categoryName:
        type: string
        example: "Book"
      products:
        type: object

  Tag:
    type: object
    properties:
      id:
        type: integer
        example: 1
      tagName:
        type: string
        example: "tag"
      category:
        type: object

  MultipleTagDTO:
    type: object
    properties:
      category:
        type: object
      tagNames:
        type: array
        items:
          type: string

  BadRequest:
    type: object
    properties:
      message:
        type: string
        example: "Bad request"

  NotFound:
    type: object
    properties:
      message:
        type: string
        example: "Product Not Found"

  InternalServerError:
    type: object
    properties:
      message:
        type: string
        example: "Internal Server Error"

  Unauthorized:
    type: object
    properties:
      message:
        type: string
        example: "Unauthorized"

paths:
  /products:
    get:
      summary: Get product details
      description: Get product details by ID
      tags:
        - Products
      parameters:
        - name: id
          in: query
          description: ID of the product to get
          required: true
          type: integer
      responses:
        200:
          description: Product found
          schema:
            $ref: "#/definitions/Product"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/BadRequest"

        404:
          description: Product not found
          schema:
            $ref: "#/definitions/NotFound"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/InternalServerError"

    delete:
      summary: Delete product
      description: Delete a product by ID
      tags:
        - Products
      parameters:
        - name: id
          in: query
          description: ID of the product to delete
          required: true
          type: integer
      responses:
        200:
          description: Product deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Product deleted successfully"

        403:
          description: Unauthorized
          schema:
            $ref: "#/definitions/Unauthorized"
        404:
          description: Product Not found
          schema:
            $ref: "#/definitions/NotFound"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/InternalServerError"

    post:
      summary: Create product
      description: Create a new product
      tags:
        - Products
      parameters:
        - in: body
          name: product
          description: Product to create
          required: true
          schema:
            $ref: "#/definitions/ProductCreationRequest"
      responses:
        201:
          description: Product created successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Product created successfully"
        403:
          description: Bad Request
          schema:
            $ref: "#/definitions/BadRequest"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/InternalServerError"

    put:
      summary: Update product
      description: Update an existing product
      tags:
        - Products
      parameters:
        - in: body
          name: product
          description: Product to update
          required: true
          schema:
            $ref: "#/definitions/ProductUpdateRequest"
      responses:
        200:
          description: Product updated successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Product updated successfully"
        403:
          description: Unauthorized
          schema:
            $ref: "#/definitions/Unauthorized"
        404:
          description: Product Not found
          schema:
            $ref: "#/definitions/NotFound"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/InternalServerError"

  /products/searchRange:
    get:
      summary: Search for products
      description: Search for products in a range
      tags:
        - Products
      parameters:
        - name: query
          in: query
          description: search query
          required: true
          type: string
        - name: startRank
          in: query
          description: start index (index start from 1)
          required: true
          type: integer
        - name: endRank
          in: query
          description: end index
          required: true
          type: integer
      responses:
        200:
          description: Search results
          schema:
            $ref: "#/definitions/ProductSearchRangeResponse"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/BadRequest"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/InternalServerError"

  /products/owner:
    get:
      summary: Search for products of a seller
      description: Search for products of a seller in a range
      tags:
        - Products
      parameters:
        - name: startIndex
          in: query
          description: start index (index start from 1)
          required: true
          type: integer
        - name: endIndex
          in: query
          description: end index
          required: true
          type: integer
        - name: sellerId
          in: query
          description: ID of the seller
          required: true
          type: integer
      responses:
        200:
          description: Search results
          schema:
            $ref: "#/definitions/ProductReadOwnerResponse"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/BadRequest"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/InternalServerError"

  /tag:
    post:
      summary: Create tag
      description: Create a new tag
      parameters:
        - in: body
          name: tag
          description: tag to create
          required: true
          schema:
            $ref:   "#/definitions/Tag"
      responses:
        200:
          description: Tag created successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Tag created successfully"

    put:
      summary: Update tag
      description: Update an existing tag
      parameters:
        - in: body
          name: tag
          description: tag to update
          required: true
          schema:
            $ref: "#/definitions/Tag"
      responses:
        200:
          description: Tag updated successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Tag updated successfully"

    delete:
      summary: Delete tag
      description: Delete a tag
      parameters:
        - in: body
          name: tag
          description: tag to delete
          required: true
          schema:
            $ref: "#/definitions/Tag"
      responses:
        200:
          description: Tag deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Tag deleted successfully"

    get:
      summary: Get tag
      description: Get a tag
      parameters:
        - in: body
          name: tag
          description: tag to get
          required: true
          schema:
            $ref: "#/definitions/Tag"
      responses:
        200:
          description: Tag retrieved successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Tag retrieved successfully"

  /category:
    post:
      summary: Create category
      description: Create a new category
      parameters:
        - in: body
          name: category
          description: category to create
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: Category created successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Category created successfully"

    put:
      summary: Update category
      description: Update an existing category
      parameters:
        - in: body
          name: category
          description: category to update
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: Category updated successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Category updated successfully"

    delete:
      summary: Delete category
      description: Delete a category
      parameters:
        - in: body
          name: category
          description: category to delete
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: Category deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Category deleted successfully"

    get:
      summary: Get category
      description: Get a category
      parameters:
        - in: body
          name: category
          description: category to get
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: Category retrieved successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Category retrieved successfully"

  /category/findCategoryById:
    get:
      summary: Get category
      description: Get a category
      parameters:
        - in: body
          name: id
          description: category ID to retrieve
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: Category retrieved successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Category retrieved successfully"

  /tags/createMultipleTagsPerCategory:
    post:
      summary: Create multiple tags
      description: Create a list of tags for a category
      parameters:
        - in: body
          name: tag
          description: tag to create
          required: true
          schema:
            $ref: "#/definitions/MultipleTagDTO"
      responses:
        200:
          description: Tags created successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Tags created successfully"